[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 1
via_ir = true
bytecode_hash = "none"
cbor_metadata = false

[profile.default.optimizer_details]
inliner = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
